// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wnzkhqdgvwutxdqyzdiu.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduemtocWRndnd1dHhkcXl6ZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0OTE4MzIsImV4cCI6MjA0OTA2NzgzMn0.hNoZqIJx4AHhFf0RJoZ8uvCMf5QQ2_h233990t1lng4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);